// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDViWsWqdjfw6a57sD7bpvhCyPYNqsOMQQ',
    appId: '1:431940402301:web:56e2365ac8bb1020ef0514',
    messagingSenderId: '431940402301',
    projectId: 'business-card-app-cb50b',
    authDomain: 'business-card-app-cb50b.firebaseapp.com',
    storageBucket: 'business-card-app-cb50b.firebasestorage.app',
    measurementId: 'G-8SJ3CSVXX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOAaypadMdewO31JX5WW8LnMeKgaWRkg8',
    appId: '1:431940402301:android:3e5743fbaf4a5de1ef0514',
    messagingSenderId: '431940402301',
    projectId: 'business-card-app-cb50b',
    storageBucket: 'business-card-app-cb50b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrGAnYJQFiUaddmG1_hTft0tCbjs2dPac',
    appId: '1:431940402301:ios:255d616753ed820aef0514',
    messagingSenderId: '431940402301',
    projectId: 'business-card-app-cb50b',
    storageBucket: 'business-card-app-cb50b.firebasestorage.app',
    iosBundleId: 'com.example.businessCardAppV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrGAnYJQFiUaddmG1_hTft0tCbjs2dPac',
    appId: '1:431940402301:ios:255d616753ed820aef0514',
    messagingSenderId: '431940402301',
    projectId: 'business-card-app-cb50b',
    storageBucket: 'business-card-app-cb50b.firebasestorage.app',
    iosBundleId: 'com.example.businessCardAppV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDViWsWqdjfw6a57sD7bpvhCyPYNqsOMQQ',
    appId: '1:431940402301:web:ea1f116a07d7d79cef0514',
    messagingSenderId: '431940402301',
    projectId: 'business-card-app-cb50b',
    authDomain: 'business-card-app-cb50b.firebaseapp.com',
    storageBucket: 'business-card-app-cb50b.firebasestorage.app',
    measurementId: 'G-TD49921TGP',
  );
}
